{
    "Description" : ["This experiment studies coordgan"],
    "dataset" : "celebA",
    "gan_loss_lambda" : 2,
    "chamfer_lambda" : 200,
    "patch_d_lambda" : 1,
    "perc_loss_lambda" : 5,
    "rgb_loss_lambda" : 5,
    "rgb_temp" : 0.01,
    "rgb_mode" : "aff",
    "rgb_down_sample_ratio" : 1,
    "path" : "data/CelebAMask-HQ/CelebA-HQ-img/",
    "ckpt" : null,
    "iter" : 300000,
    "n_sample" : 2,
    "lr" : 0.002,
    "save_checkpoint_frequency": 20000,
    "batch" : 2,
    "num_workers" : 32,
    "Generator" : "CoordGAN",
    "coords_integer_values": false,
    "size" : 128,
    "n_mlp" : 8,
    "fc_dim" : 512,
    "latent" : 512,
    "activation" : null,
    "channel_multiplier" : 2,
    "mixing" : 0.0,
    "g_reg_every" : 4,
    "Discriminator" : "Discriminator",
    "d_reg_every" : 16,
    "r1" : 10,
    "PatchDiscriminator" : "PatchDiscriminator",
    "patch_r1" : 1.0,
    "patch_min_scale" : 0.125,
    "patch_max_scale" : 0.25,
    "patch_num_crops" : 8,
    "patch_scale_capacity" : 2,
    "patch_max_nc" : 256,
    "patch_size" : 32
}
