{
    "Description" : [ "This experiment studies the encoder" ],
    "dataset" : "stanfordcar",
    "perc_loss_lambda" : 5,
    "Encoder" : "Encoder",
    "enc_input_is_latent" : true,
    "enc_consistency_lambda" : 10,
    "enc_rec_lambda" : 10,
    "enc_rec_perc_lambda" : 10,
    "rgb_temp" : 0.01,
    "rgb_mode" : "aff",
    "rgb_down_sample_ratio" : 1,
    "path" : "data/cars_train/",
    "ckpt" : null,
    "iter" : 600000,
    "n_sample" : 2,
    "lr" : 0.002,
    "save_checkpoint_frequency": 20000,
    "batch" : 2,
    "num_workers" : 32,
    "Generator" : "CoordGAN",
    "coords_integer_values": false,
    "size" : 128,
    "n_mlp" : 8,
    "fc_dim" : 512,
    "latent" : 512,
    "activation" : null,
    "channel_multiplier" : 2,
    "mixing" : 0.0,
    "g_reg_every" : 4
}
